min_sensor_dist: .05
self_see_default_padding: .00
self_see_default_scale: 1.0
self_see_links:
  - name: arm_0_link
    padding: .2
  - name: arm_1_link
    padding: .2
  - name: arm_2_link
    padding: .2
  - name: arm_3_link
    padding: .2
  - name: arm_4_link
    padding: .2
  - name: arm_5_link
    padding: .2
  - name: arm_6_link
    padding: .2
  - name: arm_7_link
    padding: .2